#!/usr/bin/env node

'use strict';

var s3sync = require('../');
var path = require('path');
var version = require(path.resolve(__dirname,'../package.json')).version;

s3sync({
  source: path.resolve(__dirname,'assets.dist'),
  // destination: `${version}/assets`,
  bucket: 's3-sync-example',
  releaseDir: `assets/${version}`,
  ignoreDotfiles: true
});
